<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <RootNamespace>SimpleTextTemplate</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Description>SimpleTextTemplateのWriter部分です。</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>templating</PackageTags>
  </PropertyGroup>

</Project>
