<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <Description>シンプルなテキストテンプレートエンジンです。</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>templating</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleTextTemplate.Writer\SimpleTextTemplate.Writer.csproj" />
  </ItemGroup>

</Project>
