<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net11.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\SimpleTextTemplate.Writer\SimpleTextTemplate.Writer.csproj" />
    <ProjectReference Include="..\SimpleTextTemplate.Tests.Core\SimpleTextTemplate.Tests.Core.csproj" />
  </ItemGroup>

</Project>
